### ISSUE TITLE
SoftwareSerial

### ISSUE THREAD

**Issue by DIYDave** [fredlllll/STIXXXWT-Arduino#1]
Hi fredlll
Thank you for sharing this library!
Is there a way to use softwareSerial instead of hardwareSerial? https://github.com/plerup/espsoftwareserial
I have tested with following code, but with Error during compile.
"no matching function for call to 'STIXXXWT::connect(SoftwareSerial*, int)'"

#include <SoftwareSerial.h>
#include <STIXXXWT.h>

SoftwareSerial swSerial(14, 12, false, 256); 
STIXXXWT display;

void setup()
{
  display.connect(&swSerial, 19200);
...

Best regards
Dave

**Comment by fredlllll** [comment]
interesting that you got hold of such a display.

i changed the code to hopefully support softwareserial too, you have to add a Serial.begin(xxx) to your setup method now though, as i cant call begin() on a Stream (the interface that both serials use). i hope this will now compile for you (its 0:30 and it could be that im a bit tired and made a mistake, tell me if it worked, so i can take another look tomorrow if not)

is there any place to take a look at what you are making?

**Comment by DIYDave** [comment]
Thank you for your quick reply to late hour. :-)
I'll try it out this weekend.
I have received one of this display for free and could still have about 40 pcs. for very low price.
I use the ".displayText" function with my own font. Here I had also go in to the library to improve it, since I use encoding = 0.
Sorry, but the project is in a very early state. So no youtube videos or other stuff for the moment.
In general it is a very tedious thing with these displays and the Chinese software to do ..
Dave
P.S. is there a description of your library?

**Comment by DIYDave** [comment]
I have tested now the use of softSerial together with the changed version. It works great!
I use a  NodeMCU board with  ESP8266 -12E.
Great Work!

**Comment by fredlllll** [comment]
good to hear that it works. when talking about "low price" how low are we speaking? the displays were fairly expensive when i tried to get them

no there is no description. basically the methods are mappings of the protocol that the display uses and are just directly translated to commands, so the datasheet of the protocol would be the description mostly.

**Comment by DIYDave** [comment]
I have a customer who would sell me 40 pcs. All new and in original packaging. I think I could resell it for $ 50 / piece. Or $ 300 for a box of 8 pieces.
It is this type of display: https://www.aliexpress.com/store/product/5-STONE-TFT-LCD-Module-with-CPU-serial-interface-for-touch-controller/204204_32268723222.html
I added a function "Arbitrary Small Format Image Display" (0x70 01) to the library described in the manual.
We can also communicate directly in German. -> d(dot)waldesbuehl(at)hispeed(dot)ch

![Photo](https://cloud.githubusercontent.com/assets/25878044/25562947/0062cdae-2d92-11e7-917e-65ce7787e042.jpg)
